---
abstract: 'Minimalistic routing sugar for your Plack'
author:
  - 'dann <techmemo@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Plack::Test: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-Dispatcher-Simple
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Filter::Util::Call: 0
  Plack::Request: 0.09
  Router::Simple: 0.07
  Scalar::Util: 0
  Try::Tiny: 0.06
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
